### ISSUE TITLE
[Discussion] Discuss the principal of whether making a repo into deepmodeling

### ISSUE THREAD

**Issue by likefallwind** [deepmodeling/community#15]
At present, there are some repos in deepmodeling, but these repos only act as like online disk -- a place to store data.

Maybe we should discuss how to deal with such repo.

In my opinion:
1. If a repo need more concern; or it need community to continueous maintain, then the repo should put into deepmodeling.
2. If a repo only act as online disk, then it should not be put into deepmodeling. We make a new orinizaiton named [deepmodeling_activity](https://github.com/deepmodeling-activity) to store such things.

What do you think?

**Comment by likefallwind** [comment]
@amcadmus @weihuayi @mohanchen @KuangYu @zjgemi @njzjz @AnguseZhang

**Comment by mohanchen** [comment]
agree

**Comment by wanghan-iapcm** [comment]
large files should not be put in code repositories. rather one may use this solution: https://git-lfs.github.com/

**Comment by likefallwind** [comment]
> large files should not be put in code repositories. rather one may use this solution: https://git-lfs.github.com/

I agree. But sometimes it is not large files. Just like a book or a scientific paper.
