### ISSUE TITLE
安装

### ISSUE THREAD

**Issue by ann25** [deepmodeling/community#24]
您好，我在1.2configure上遇到了问题。前面的步骤都是跟着教程来的，除了cuda版本是10.1，因此改了pytorch的安装版本外。但是在. configure.sh --use_pytorch 这一步中出现了以下的问题
![2023-04-10 21-23-51屏幕截图](https://user-images.githubusercontent.com/129950334/230910105-4284b7fa-b682-461d-985b-544760d227f3.png)
请问该怎么解决呢

**Comment by ann25** [comment]
deep flame -deepmodeling安装问题

**Comment by njzjz** [comment]
Hi, please ask questions in the deep-flame repository: https://github.com/deepmodeling/deepflame-dev
