### ISSUE TITLE
training with subset of atoms

### ISSUE THREAD

**Issue by Miserablegit75** [deepmodeling/community#5]
Hi – I have a DFT trajectory that I’d like to use to train a neural network forcefield with deepmd-kit. I’ve put the trajectory into a format that dpdata can read. However, the original simulation was complicated by the presence of “frozen” atoms that were constrained to be motionless. By construction, the frozen atoms have zero force components in the trajectory file. When training, we want to include the frozen atoms in the neighbor lists when computing the force on neighboring non-frozen atoms; but we never want to compute the force on a frozen atom because we would then be training with a non-physical force. Does deepmd-kit or dpdata have the ability to train using only a subset of the atoms in the simulation? That is, can we tell deepmd-kit to train a neural network forcefield using only the forces on the non-frozen atoms, even when computation of those forces could include contributions from the frozen atoms? Thanks.

**Comment by njzjz** [comment]
Oh, I think I understand what you mean. Did you provide an external force to make the atoms frozen? If so, do you have the original forces?

**Comment by Miserablegit75** [comment]
For the sake of argument, assume we are going to perform the calculation using a classical forcefield. We need to compute the forces on every non-frozen atom, and these forces can include contributions from frozen atoms that are within the cutoff length. We do not need to compute the forces on the frozen atoms because by construction they can’t move; also, if we were to try to compute the forces on the frozen atoms we would get nonsense results. The frozen atoms in effect provide a boundary in the simulation and must remain frozen because they are missing neighbors outside the boundary. 

 

Now consider training the neural net. We want to describe correctly the atomic configuration around each non-frozen atom. This configuration must include the frozen atoms on the boundary of the simulation when necessary. If we were to try to include the frozen atoms in the training, the atomic configuration would be nonphysical because they are missing neighbors outside the boundary. 

 

I had to back out forces from the original DFT trajectory because only positions and velocities were saved. (The calculation took two years to perform.) I have zero forces on the frozen atoms because that’s what the various Verlet formulae yield when applied to motionless atoms.

 

Let me know if this makes sense…

**Comment by Miserablegit75** [comment]
No, the atoms were just fixed in the original CP2K simulation. I do not have any original forces on the frozen atoms.

**Comment by njzjz** [comment]
You can append a NumPy file called `atom_pref.npy` (shape: Nframes * Natoms) which provides training weight of each atoms, where the weight of frozen atoms can be set to 0.
Then, use `start_pref_pf` and `limit_pref_pf` keyword instead of `start_pref_f` and `limit_pref_f`. (see https://docs.deepmodeling.org/projects/deepmd/en/v2.1.0/train/train-input.html for details)
It will try to fit forces only on atoms with weights.

If you energy was also modified (so it cannot match forces), you'd better set pref_e to 0 as well.

**Comment by Miserablegit75** [comment]
Ah… that looks like it might be a solution. I’ll get to work on this and let you know what happens. You can close the issue. Many thanks!

**Comment by njzjz** [comment]
> You can close the issue.

@wanghan-iapcm, require your help to to do..
